name: build

permissions:
  contents: write

on:
  push:
    branches:
      - main
  schedule:
    - cron: "25 23 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      build_needed: ${{ steps.check.outputs.build_needed }}
      caddyver: ${{ steps.check.outputs.caddyver }}
    steps:
      - name: check update
        id: check
        run: |
          curl(){
            $(type -P curl) "$@" -L -q --retry 5 --retry-delay 10 --retry-max-time 60
          }
          latest_CADDY_VERSION=$(curl https://api.github.com/repos/caddyserver/caddy/releases/latest  | jq -r ".tag_name")
          local_CADDY_VERSION=$(curl https://api.github.com/repos/AsenHu/caddy-builder/releases | jq '.[] | select(.tag_name == "cfdnstls") | .name' -r)
          if [ "$latest_CADDY_VERSION" == "$local_CADDY_VERSION" ]
          then
            echo "caddy is already the latest version $latest_CADDY_VERSION"
            echo "build_needed=false" >> $GITHUB_OUTPUT
          else
            echo "caddy is not the latest version, start building"
            echo "build_needed=true" >> $GITHUB_OUTPUT
          fi
          echo "caddyver=$latest_CADDY_VERSION" >> $GITHUB_OUTPUT

  cache:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.build_needed == 'true'
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version: 'stable'
          check-latest: true
      - run: go mod tidy -e
      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
          key: cache-${{ github.sha }}-${{ github.run_number }}

  release:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.build_needed == 'true'
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: cfdnstls
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true 
          repo: ${{ github.repository	}}
      - run: | 
          curl https://api.github.com/repos/caddyserver/caddy/releases/latest | jq .body -r | \
          sed 's#\(\#\)\([0-9]\+\)#\[&\]\(https://github.com/caddyserver/caddy/pull/\2\)#g' | \
          sed 's#[0-9a-fA-F]\{8\}#\[`&`\]\(https://github.com/caddyserver/caddy/commit/&\)#g' \
          > changelog.md
      - run: |
          {
            date
            echo ${{ needs.check.outputs.caddyver }}
            date +%s
          } > version.txt
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh release create "cfdnstls" \
              --repo="${{ github.repository	}}" \
              --title="${{ needs.check.outputs.caddyver }}" \
              -F changelog.md
      - uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "version.txt"
          tag: cfdnstls

  build:
    strategy:
      matrix:
        goamd: [ v1, v2, v3, v4 ]
    env:
      GOOS: linux
      GOARCH: amd64
      GOAMD64: ${{ matrix.goamd }}
      CGO_ENABLED: 0
    runs-on: ubuntu-latest
    needs: [ cache, release ]
    if: needs.check.outputs.build_needed == 'true'
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
          key: cache-
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version: 'stable'
          check-latest: true
      - name: build
        run : |
          go build -o "caddy-$GOOS-$GOARCH-${{ matrix.goamd }}"
      - name: Upload artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: "caddy-${{ env.GOOS }}-${{ env.GOARCH }}-${{ env.GOAMD64 }}"
          path: "caddy-${{ env.GOOS }}-${{ env.GOARCH }}-${{ env.GOAMD64 }}"
      - uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "caddy-${{ env.GOOS }}-${{ env.GOARCH }}-${{ env.GOAMD64 }}"
          tag: cfdnstls
