name: build

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - '!.github/**'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        run: |
          run: gh pr review --approve "${{github.event.pull_request.html_url}}"
          PR_URL: ${{github.event.pull_request.html_url}}