name: build

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if only .github files are changed
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr diff --name-only > changed_files.txt
          cat changed_files.txt
          if grep -vqE '^\.github/' changed_files.txt
          then
            echo "Only .github files are allowed to be changed."
            echo "build=false" >> $GITHUB_ENV
          else
            echo "Should build."
            echo "build=true" >> $GITHUB_ENV
          fi
      - name: Checkout code
        if: steps.check.outputs.build == 'true'
        uses: actions/checkout@v4
      - name: Set up Go
        if: steps.check.outputs.build == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true
      - name: linux-amd64-v1
        if: steps.check.outputs.build == 'true'
        env:
          GOOS: linux
          GOARCH: amd64
          GOAMD64: v1
          CGO_ENABLED: 0
        run: |
          go build -o caddy -ldflags "-s -w"
          echo "build finished"
          xz -ze9vv caddy
          mv caddy.xz "caddy-$GOOS-$GOARCH-$GOAMD64.xz"
      - name: delete release
        if: steps.check.outputs.build == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="$(grep 'github.com/caddyserver/caddy/v2' go.mod | awk '{print $2}')"
          gh release delete --yes \
            --repo="${{github.repository}}" \
            --cleanup-tag "$tag" || echo "Nothing to delete."
      - name: linux-amd64-v2
        if: steps.check.outputs.build == 'true'
        env:
          GOOS: linux
          GOARCH: amd64
          GOAMD64: v2
          CGO_ENABLED: 0
        run: |
          go build -o caddy -ldflags "-s -w"
          echo "build finished"
          xz -ze9vv caddy
          mv caddy.xz "caddy-$GOOS-$GOARCH-$GOAMD64.xz"
      - name: linux-amd64-v3
        if: steps.check.outputs.build == 'true'
        env:
          GOOS: linux
          GOARCH: amd64
          GOAMD64: v3
          CGO_ENABLED: 0
        run: |
          go build -o caddy -ldflags "-s -w"
          echo "build finished"
          xz -ze9vv caddy
          mv caddy.xz "caddy-$GOOS-$GOARCH-$GOAMD64.xz"
      - name: linux-amd64-v4
        if: steps.check.outputs.build == 'true'
        env:
          GOOS: linux
          GOARCH: amd64
          GOAMD64: v4
          CGO_ENABLED: 0
        run: |
          go build -o caddy -ldflags "-s -w"
          echo "build finished"
          xz -ze9vv caddy
          mv caddy.xz "caddy-$GOOS-$GOARCH-$GOAMD64.xz"
      - name: upload
        if: steps.check.outputs.build == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="$(grep 'github.com/caddyserver/caddy/v2' go.mod | awk '{print $2}')"
          gh release create "$tag" \
            --repo="${{github.repository}}" \
            --title="$tag" \
            --generate-notes
          gh release upload "$tag" "./caddy-linux-amd64-v1.xz" \
            --clobber \
            --repo="${{github.repository}}"
          gh release upload "$tag" "./caddy-linux-amd64-v2.xz" \
            --clobber \
            --repo="${{github.repository}}"
          gh release upload "$tag" "./caddy-linux-amd64-v3.xz" \
            --clobber \
            --repo="${{github.repository}}"
          gh release upload "$tag" "./caddy-linux-amd64-v4.xz" \
            --clobber \
            --repo="${{github.repository}}"
      - name: Approve PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr review --approve || echo "It's not a PR."